/**:
  ros__parameters:
    sensor_ip: 192.168.2.201
    launch_hw: true
    frame_id: aeva
    sensor_model: Aeries2
    setup_sensor: true
    diag_span: 1000
    dithering_enable_ego_speed: 40.0
    dithering_pattern_option: dithering_pattern_1
    ele_offset_rad: 0.0
    elevation_auto_adjustment: false
    enable_frame_dithering: false
    enable_frame_sync: true
    flip_pattern_vertically: false
    frame_sync_offset_in_ms: 999
    frame_sync_type: nearest_second
    frame_synchronization_on_rising_edge: true
    hfov_adjustment_deg: 0.0
    hfov_rotation_deg: 0.0
    highlight_ROI: false
    horizontal_fov_degrees: 110Degrees
    roi_az_offset_rad: 0.0
    vertical_pattern: 40-14.4-ROI
